// fetch payment histories
export const FETCH_PAYMENT_HISTORIES_REQUEST =
  'paymentHistory/FETCH_PAYMENT_HISTORIES_REQUEST';
export const FETCH_PAYMENT_HISTORIES_SUCCESS =
  'paymentHistory/FETCH_PAYMENT_HISTORIES_SUCCESS';
export const FETCH_PAYMENT_HISTORIES_FAILURE =
  'paymentHistory/FETCH_PAYMENT_HISTORIES_SUCCESS';

// settle pending payment
export const SETTLE_PENDING_PAYMENT_REQUEST = `paymentHistory/SETTLE_PENDING_PAYMENT_REQUEST`;
export const SETTLE_PENDING_PAYMENT_REQUEST_SUCCESS =
  'paymentHistory/SETTLE_PENDING_PAYMENT_REQUEST_SUCCESS';
export const SETTLE_PENDING_PAYMENT_REQUEST_FAILURE =
  'paymentHistory/SETTLE_PENDING_PAYMENT_REQUEST_SUCCESS';
