// fetch posts by slug
export const FETCH_POSTS_BY_SLUG_REQUEST = 'wpPost/FETCH_POSTS_BY_SLUG_REQUEST';
export const FETCH_POSTS_BY_SLUG_SUCCESS = 'wpPost/FETCH_POSTS_BY_SLUG_SUCCESS';
export const FETCH_POSTS_BY_SLUG_FAILURE = 'wpPost/FETCH_POSTS_BY_SLUG_FAILURE';

export const SET_POST = 'wpPost/SET_POST';
