image: zazukoians/node-java

pipelines:
    pull-requests:
      '**':
        - parallel:
          - step:
              name: Cypress E2E Testing
              caches:
                - npm
                - firebase-emulator
                - cypress
              script:
                - apt-get update
                - apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
                - npm install
                - cd web
                - npm install
                - cd ../shared
                - npm install
                - cd ..
                - npm run cypress:test:ci
          - step:
              name: Eslint Validation
              caches:
                - npm
              script:
                - cd web
                - npm install
                - npm run eslint:check
                - cd ../shared
                - npm install
                - npm run eslint:check
                - cd ../admin
                - npm install
                - npm run eslint:check
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
    firebase-emulator: $HOME/.cache/firebase/emulators
