// fetch subscribers
export const FETCH_SUBSCRIBERS_REQUEST = 'user/FETCH_SUBSCRIBERS_REQUEST';
export const FETCH_SUBSCRIBERS_SUCCESS = 'user/FETCH_SUBSCRIBERS_SUCCESS';
export const FETCH_SUBSCRIBERS_FAILURE = 'user/FETCH_SUBSCRIBERS_FAILURE';

// fetch purchased item
export const FETCH_PURCHASE_REQUEST = 'purchase/FETCH_PURCHASE_REQUEST';
export const FETCH_PURCHASE_SUCCESS = 'purchase/FETCH_PURCHASE_SUCCESS';
export const FETCH_PURCHASE_FAILURE = 'purchase/FETCH_PURCHASE_FAILURE';

// update subscribers
export const UPDATE_SUBSCRIBER_REQUEST = 'user/UPDATE_SUBSCRIBER_REQUEST';
export const UPDATE_SUBSCRIBER_SUCCESS = 'user/UPDATE_SUBSCRIBER_SUCCESS';
export const UPDATE_SUBSCRIBER_FAILURE = 'user/UPDATE_SUBSCRIBER_FAILURE';
