// add video lecture
export const ADD_VIDEO_LECTURE_REQUEST =
  'videoLecture/ADD_VIDEO_LECTURE_REQUEST';
export const ADD_VIDEO_LECTURE_SUCCESS =
  'videoLecture/ADD_VIDEO_LECTURE_SUCCESS';
export const ADD_VIDEO_LECTURE_FAILURE =
  'videoLecture/ADD_VIDEO_LECTURE_FAILURE';

// fetch videos
export const FETCH_VIDEO_LECTURES_REQUEST =
  'videoLecture/FETCH_VIDEO_LECTURES_REQUEST';
export const FETCH_VIDEO_LECTURES_SUCCESS =
  'videoLecture/FETCH_VIDEO_LECTURES_SUCCESS';
export const FETCH_VIDEO_LECTURES_FAILURE =
  'videoLecture/FETCH_VIDEO_LECTURES_FAILURE';

// update video
export const UPDATE_VIDEO_LECTURE_REQUEST =
  'videoLecture/UPDATE_VIDEO_LECTURE_REQUEST';
export const UPDATE_VIDEO_LECTURE_SUCCESS =
  'videoLecture/UPDATE_VIDEO_LECTURE_SUCCESS';
export const UPDATE_VIDEO_LECTURE_FAILURE =
  'videoLecture/UPDATE_VIDEO_LECTURE_FAILURE';

// delete videos
export const DELETE_VIDEO_LECTURES_REQUEST =
  'videoLecture/DELETE_VIDEO_LECTURES_REQUEST';
export const DELETE_VIDEO_LECTURES_SUCCESS =
  'videoLecture/DELETE_VIDEO_LECTURES_SUCCESS';
export const DELETE_VIDEO_LECTURES_FAILURE =
  'videoLecture/DELETE_VIDEO_LECTURES_FAILURE';
