// fetch instructors
export const FETCH_INSTRUCTORS_REQUEST = 'instructor/FETCH_INSTRUCTORS_REQUEST';
export const FETCH_INSTRUCTORS_SUCCESS = 'instructor/FETCH_INSTRUCTORS_SUCCESS';
export const FETCH_INSTRUCTORS_FAILURE = 'instructor/FETCH_INSTRUCTORS_FAILURE';

// add instructors
export const CREATE_INSTRUCTOR_REQUEST = 'instructor/CREATE_INSTRUCTOR_REQUEST';
export const CREATE_INSTRUCTOR_SUCCESS = 'instructor/CREATE_INSTRUCTOR_SUCCESS';
export const CREATE_INSTRUCTOR_FAILURE = 'instructor/CREATE_INSTRUCTOR_FAILURE';

// delete instructors
export const DELETE_INSTRUCTORS_REQUEST =
  'instructor/DELETE_INSTRUCTORS_REQUEST';
export const DELETE_INSTRUCTORS_SUCCESS =
  'instructor/DELETE_INSTRUCTORS_SUCCESS';
export const DELETE_INSTRUCTORS_FAILURE =
  'instructor/DELETE_INSTRUCTORS_FAILURE';

// update instructors
export const UPDATE_INSTRUCTOR_REQUEST = 'instructor/UPDATE_INSTRUCTOR_REQUEST';
export const UPDATE_INSTRUCTOR_SUCCESS = 'instructor/UPDATE_INSTRUCTOR_SUCCESS';
export const UPDATE_INSTRUCTOR_FAILURE = 'instructor/UPDATE_INSTRUCTOR_FAILURE';
