// fetch recommended manuals
export const FETCH_MANUALS_REQUEST = 'manual/FETCH_MANUALS_REQUEST';
export const FETCH_MANUALS_SUCCESS = 'manual/FETCH_MANUALS_SUCCESS';
export const FETCH_MANUALS_FAILURE = 'manual/FETCH_MANUALS_FAILURE';

// fetch recommended manuals
export const FETCH_RECOMMENDED_MANUALS_REQUEST =
  'manual/FETCH_RECOMMENDED_MANUALS_REQUEST';
export const FETCH_RECOMMENDED_MANUALS_SUCCESS =
  'manual/FETCH_RECOMMENDED_MANUALS_SUCCESS';
export const FETCH_RECOMMENDED_MANUALS_FAILURE =
  'manual/FETCH_RECOMMENDED_MANUALS_FAILURE';

export const FETCH_LAST_BOUGHT_MANUALS_REQUEST =
  'manual/FETCH_LAST_BOUGHT_MANUALS_REQUEST';
export const FETCH_LAST_BOUGHT_MANUALS_SUCCESS =
  'manual/FETCH_LAST_BOUGHT_MANUALS_SUCCESS';
export const FETCH_LAST_BOUGHT_MANUALS_FAILURE =
  'manual/FETCH_LAST_BOUGHT_MANUALS_FAILURE';

// set manual data
export const SET_MANUAL_DATA = 'manual/SET_MANUAL_DATA';

// set recommended manuals list
export const SET_RECOMMENDED_MANUALS = 'manual/SET_RECOMMENDED_MANUALS';

// set recently bought manuals
export const SET_LAST_BOUGHT_MANUALS = 'manual/SET_LAST_BOUGHT_MANUALS';
