// fetch project contents
export const FETCH_PROJECT_CONTENTS_REQUEST =
  'projectContent/FETCH_PROJECT_CONTENTS_REQUEST';
export const FETCH_PROJECT_CONTENTS_SUCCESS =
  'projectContent/FETCH_PROJECT_CONTENTS_SUCCESS';
export const FETCH_PROJECT_CONTENTS_FAILURE =
  'projectContent/FETCH_PROJECT_CONTENTS_FAILURE';

// fetch recommended project contents
export const FETCH_RECOMMENDED_PROJECT_CONTENTS_REQUEST =
  'projectContent/FETCH_RECOMMENDED_PROJECT_CONTENTS_REQUEST';
export const FETCH_RECOMMENDED_PROJECT_CONTENTS_SUCCESS =
  'projectContent/FETCH_RECOMMENDED_PROJECT_CONTENTS_SUCCESS';
export const FETCH_RECOMMENDED_PROJECT_CONTENTS_FAILURE =
  'projectContent/FETCH_RECOMMENDED_PROJECT_CONTENTS_FAILURE';

// fetch multiple
export const FETCH_LAST_BOUGHT_PROJECT_CONTENTS_REQUEST =
  'projectContent/FETCH_LAST_BOUGHT_PROJECT_CONTENTS_REQUEST';
export const FETCH_LAST_BOUGHT_PROJECT_CONTENTS_SUCCESS =
  'projectContent/FETCH_LAST_BOUGHT_PROJECT_CONTENTS_SUCCESS';
export const FETCH_LAST_BOUGHT_PROJECT_CONTENTS_FAILURE =
  'projectContent/FETCH_LAST_BOUGHT_PROJECT_CONTENTS_FAILURE';

// set project content data
export const SET_PROJECT_CONTENT_DATA =
  'projectContent/SET_PROJECT_CONTENT_DATA';

// set recommended project contents list
export const SET_RECOMMENDED_PROJECT_CONTENTS =
  'projectContent/SET_RECOMMENDED_PROJECT_CONTENTS';

// set recently bought project contents
export const SET_LAST_BOUGHT_PROJECT_CONTENTS =
  'projectContent/SET_LAST_BOUGHT_PROJECT_CONTENTS';
