export const UPDATE_PAYMENT_HISTORY_REQUEST =
  'paymentHistory/UPDATE_PAYMENT_HISTORY_REQUEST';
export const UPDATE_PAYMENT_HISTORY_SUCCESS =
  'paymentHistory/UPDATE_PAYMENT_HISTORY_SUCCESS';
export const UPDATE_PAYMENT_HISTORY_FAILED =
  'paymentHistory/UPDATE_PAYMENT_HISTORY_FAILED';
