// create ea program
export const ADD_EA_PROGRAM_REQUEST = 'eaProgram/ADD_EA_PROGRAM_REQUEST';
export const ADD_EA_PROGRAM_SUCCESS = 'eaProgram/ADD_EA_PROGRAM_SUCCESS';
export const ADD_EA_PROGRAM_FAILURE = 'eaProgram/ADD_EA_PROGRAM_FAILURE';

// fetch ea programs
export const FETCH_EA_PROGRAMS_REQUEST = 'eaProgram/FETCH_EA_PROGRAMS_REQUEST';
export const FETCH_EA_PROGRAMS_SUCCESS = 'eaProgram/FETCH_EA_PROGRAMS_SUCCESS';
export const FETCH_EA_PROGRAMS_FAILURE = 'eaProgram/FETCH_EA_PROGRAMS_FAILURE';

// update ea program
export const UPDATE_EA_PROGRAM_REQUEST = 'eaProgram/UPDATE_EA_PROGRAM_REQUEST';
export const UPDATE_EA_PROGRAM_SUCCESS = 'eaProgram/UPDATE_EA_PROGRAM_SUCCESS';
export const UPDATE_EA_PROGRAM_FAILURE = 'eaProgram/UPDATE_EA_PROGRAM_FAILURE';

// delete ea program
export const DELETE_EA_PROGRAMS_REQUEST =
  'eaProgram/DELETE_EA_PROGRAMS_REQUEST';
export const DELETE_EA_PROGRAMS_SUCCESS =
  'eaProgram/DELETE_EA_PROGRAMS_SUCCESS';
export const DELETE_EA_PROGRAMS_FAILURE =
  'eaProgram/DELETE_EA_PROGRAMS_FAILURE';
