// set user
export const SET_USER = 'user/SET_USER';

// clear user data
export const CLEAR_USER = 'user/CLEAR_USER';

// update user
export const UPDATE_USER_REQUEST = 'user/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'user/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'user/UPDATE_USER_FAILURE';

// fetch user
export const FETCH_USER_REQUEST = 'user/FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'user/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'user/FETCH_USER_FAILURE';

// fetch instructors
export const FETCH_INSTRUCTORS_REQUEST = 'user/FETCH_INSTRUCTORS_REQUEST';
export const FETCH_INSTRUCTORS_SUCCESS = 'user/FETCH_INSTRUCTORS_SUCCESS';
export const FETCH_INSTRUCTORS_FAILURE = 'user/FETCH_INSTRUCTORS_FAILURE';

// set instructors
export const SET_INSTRUCTORS_LIST = 'user/SET_INSTRUCTORS_LIST';

// add stripe card
export const ADD_CARD_REQUEST = 'user/ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'user/ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'user/ADD_CARD_FAILURE';

// delete stripe card
export const DELETE_CARD_REQUEST = 'user/DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'user/DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'user/DELETE_CARD_FAILURE';

// purchase content
export const PURCHASE_CONTENT_REQUEST = 'user/PURCHASE_CONTENT_REQUEST';
export const PURCHASE_CONTENT_SUCCESS = 'user/PURCHASE_CONTENT_SUCCESS';
export const PURCHASE_CONTENT_FAILURE = 'user/PURCHASE_CONTENT_FAILURE';

// dismiss request
export const DISMISS_USER_REQUESTS = 'user/DISMISS_USER_REQUESTS';

// purchase points
export const PURCHASE_POINTS_CARD_REQUEST = 'user/PURCHASE_POINTS_CARD_REQUEST';
export const PURCHASE_POINTS_CARD_SUCCESS = 'user/PURCHASE_POINTS_CARD_SUCCESS';
export const PURCHASE_POINTS_CARD_FAILURE = 'user/PURCHASE_POINTS_CARD_FAILURE';

export const PURCHASE_POINTS_PAYPAL_REQUEST =
  'user/PURCHASE_POINTS_PAYPAL_REQUEST';
export const PURCHASE_POINTS_PAYPAL_SUCCESS =
  'user/PURCHASE_POINTS_PAYPAL_SUCCESS';
export const PURCHASE_POINTS_PAYPAL_FAILURE =
  'user/PURCHASE_POINTS_PAYPAL_FAILURE';

// update user last log in value
export const SET_LAST_LOG_IN_REQUEST = 'user/SET_LAST_LOG_IN_REQUEST';
export const SET_LAST_LOG_IN_SUCCESS = 'user/SET_LAST_LOG_IN_SUCCESS';
export const SET_LAST_LOG_IN_FAILURE = 'user/SET_LAST_LOG_IN_FAILURE';

// claim giveaways
export const CLAIM_GIVEAWAYS_REQUEST = 'user/CLAIM_GIVEAWAYS_REQUEST';
export const CLAIM_GIVEAWAYS_SUCCESS = 'user/CLAIM_GIVEAWAYS_SUCCESS';
export const CLAIM_GIVEAWAYS_FAILURE = 'user/CLAIM_GIVEAWAYS_FAILURE';

// Update mailbox settings
export const UPDATE_MAILBOX_SETTINGS_REQUEST =
  'user/UPDATE_MAILBOX_SETTINGS_REQUEST';
export const UPDATE_MAILBOX_SETTINGS_SUCCESS =
  'user/UPDATE_MAILBOX_SETTINGS_SUCCESS';
export const UPDATE_MAILBOX_SETTINGS_FAILURE =
  'user/UPDATE_MAILBOX_SETTINGS_FAILURE';
